<table>
    <tr>
      <td>Minería de datos y el Paradigma Big Data  (<b>MIN</b>) - Facultad de Informática - UCM</td>
      <td><img src="https://biblioteca.ucm.es/data/cont/media/www/pag-88746//escudo.jpg"  width=50/></td>
    </tr>
</table>

## Práctica 0: Introducción a Python - Análisis de Datos de Streaming y Gaming
### Pablo C. Cañizares (Facultad de Informática - UCM)



Por favor, no olvides escribir aquí tu nombre y el número de puesto

Nombre:                 Puesto:

**Instrucciones**

* Completa las casillas indicadas 
* Cuando hayas terminado selecciona *File* + *Download*
* Grabar el fichero en el disco (por ejemplo en la carpeta c:\hlocal) con nombre *NombreDelEstudiante.ipynb*
* Finalmente subir este fichero al *Campus Virtual*.

---
## Contexto

Imagina que trabajas como **Data Analyst** en una startup que desarrolla una app que combina streaming de música, estadísticas de videojuegos y redes sociales. Tu trabajo es analizar los datos de los usuarios para mejorar las recomendaciones y detectar tendencias.

En esta práctica trabajarás con datos similares a los que manejan plataformas como **Spotify**, **Twitch**, **TikTok** o **Steam**.

---

## Ejercicio 1 - Minutos de escucha por género musical

Tienes el historial de reproducciones de un usuario de Spotify. Cada registro contiene dos listas paralelas: una con los géneros musicales y otra con los minutos escuchados en cada sesión:

```python
generos = ["hiphop", "pop", "hiphop", "trap", "pop", "k-pop"]
minutos = [45, 30, 60, 25, 15, 40]
```

Tu objetivo es calcular el **tiempo medio de escucha por género**. Para ello:

1. Agrupa todas las sesiones correspondientes al mismo género.
2. Calcula la media de minutos asociados a cada uno.
3. Devuelve el resultado en forma de diccionario, donde la clave sea el género y el valor la media calculada.

Pista: Para saber si una clave existe en un diccionario se utiliza `in` o `not in` si consultamos que no exista.

In [2]:
generos = ["hiphop", "pop", "hiphop", "trap", "pop", "k-pop"]
minutos = [45, 30, 60, 25, 15, 40]

### Solución

In [3]:
#Solución ...

tam= len(generos)
dict = {}
dict2={}
for i in range(tam):
    if(dict.get(generos[i])):
        x = dict.get(generos[i])
        y =dict2.get(generos[i])
        x=(x*y+minutos[i])/(y+1)
        y+=1
        dict.update({generos[i]:x})
        dict2.update({generos[i]:y})
    else:
        dict[generos[i]]=minutos[i]
        dict2[generos[i]]=1

print(dict)
    
    

{'hiphop': 52.5, 'pop': 22.5, 'trap': 25, 'k-pop': 40}


---

## Ejercicio 2 - Puntuaciones en FMS World Series

Tienes el registro de puntuaciones de batallas de la [**FMS World Series**](https://fms.tv/). Tienes dos listas paralelas: una con los nombres de los freestylers y otra con las puntuaciones obtenidas en cada batalla:

- [Aczino](https://es.wikipedia.org/wiki/Aczino) - MC mexicano, múltiple campeón internacional
- [Chuty](https://es.wikipedia.org/wiki/Chuty) - MC español, múltiple campeón internacional
- [Gazir](https://www.redbull.com/es-es/artist/gazir-perfil) - MC español, campeón actual FMS World Series
- [Teorema](https://rap.fandom.com/es/wiki/Teorema) - MC chileno, campeón RedBull Batalla chile

```python
mcs = ["Aczino", "Chuty", "Aczino", "Gazir", "Chuty", "Gazir", "Teorema"]
puntuaciones = [4.5, 4.8, 4.9, 4.2, 4.6, 4.7, 4.3]
```

Calcula, para cada MC, la **puntuación mínima y máxima** registradas. El resultado debe devolverse en un diccionario donde:
- La clave sea el nombre del freestyler
- El valor sea el máximo de puntuación obtenida
- Extra: si el ejercicio te ha resultado sencillo, extiende el resultado el valor sea un diccionario con las claves `"min"` y `"max"` conteniendo la puntuación mínima y máxima respectivamente.

Por ejemplo:

```python
{"Aczino": {"min": 4.5, "max": 4.9}, "Chuty": {"min": 4.6, "max": 4.8}, "Gazir": {"min": 4.2, "max": 4.7}, "Teorema": {"min": 4.3, "max": 4.3}}
```

In [4]:
mcs = ["Aczino", "Chuty", "Aczino", "Gazir", "Chuty", "Gazir", "Teorema"]
puntuaciones = [4.5, 4.8, 4.9, 4.2, 4.6, 4.7, 4.3]

### Solución

In [5]:
records = {}  # mc -> {"min": ..., "max": ...}

#Solución
tam=len(mcs)
dict={}
for i in range(tam):
    if(dict.get(mcs[i])):
        x = dict.get(mcs[i])
        minim=x.get('min')
        maxim=x.get('max')
        if(puntuaciones[i]>maxim):
            maxim = puntuaciones[i]
        if(puntuaciones[i] < minim):
            minim = puntuaciones[i]
        x.update({'min':minim,'max':maxim})
        dict.update({mcs[i]:x})
    else:
        x ={'min': puntuaciones[i], 'max':puntuaciones[i]}
        dict[mcs[i]]=x

records = dict

print(records)

{'Aczino': {'min': 4.5, 'max': 4.9}, 'Chuty': {'min': 4.6, 'max': 4.8}, 'Gazir': {'min': 4.2, 'max': 4.7}, 'Teorema': {'min': 4.3, 'max': 4.3}}


---

## Ejercicio 3 - Limpieza de datos: filtrar tiempos de pantalla inválidos

Tienes datos del tiempo de pantalla diario (en horas) de usuarios en TikTok, pero algunos registros tienen errores de medición:

```python
screen_time = [3.5, 25.0, -2.0, 5.2, None, 8.1, 30.0, 2.0]
```

Genera una nueva lista con solo los valores válidos:

* Valores numéricos entre 0 y 24 horas (ambos incluidos).
* Excluyendo cualquier valor `None` (para saber si un valor no es `None` se consulta asi: `is not None`).


In [6]:
screen_time = [3.5, 25.0, -2.0, 5.2, None, 8.1, 30.0, 2.0]

### Solución

In [7]:
#Solución
tam = len(screen_time)
validos = []

for i in range(tam):
    x = screen_time[i]
    if(x is not None and x >= 0 and x <= 24):
        validos.append(x)

print(validos)




[3.5, 5.2, 8.1, 2.0]


---
## Ejercicio 4 - Clasificar streamers por franja de viewers

Tienes datos de streamers de [Twitch](https://www.twitch.tv/) con su media de espectadores:

- [IlloJuan](https://www.twitch.tv/illojuan) - Streamer de variedades y andalusí :)
- [Ibai](https://www.twitch.tv/ibai) - Streamer, presentador y titán
- [Mayichi](https://www.twitch.tv/mayichi) - Streamer de gaming
- [ElXokas](https://www.twitch.tv/elxokas) - Streamer conocido por WoW, pero esto no es un juego
- [Cristinini](https://www.twitch.tv/cristinini) - Streamer de variedades

```python
streamers = [("IlloJuan", 35000), ("Ibai", 85000), ("Mayichi", 3500), ("ElXokas", 42000), ("Cristinini", 4200), ("Persjansen", 800)]
```

Clasifica a los streamers en tres categorías según sus viewers:

* **Pequeño:** menos de 1000 viewers
* **Medio:** de 1000 a 10000 viewers
* **Grande:** más de 10000 viewers

Devuelve un diccionario con el conteo de streamers en cada categoría:

```python
{"pequeño": 1, "medio": 2, "grande": 3}
```

Pista: La salida es una lista de tuplas, las tuplas son muy sencillas, puedes ver su funcionamiento [aqui](https://www.w3schools.com/python/python_tuples.asp)

In [8]:
streamers = [("IlloJuan", 35000), ("Ibai", 85000), ("Mayichi", 3500), ("ElXokas", 42000), ("Cristinini", 4200), ("Persjansen", 800)]

### Solución

In [9]:
#Solución
tam=len(streamers)
dict={'pequeño': 0,'medio': 0,'grande': 0}
for i in range(tam):
    x = streamers[i]
    views = x[1]
    if (views > 10000):
        y = dict.get('grande')
        y+=1
        dict.update({'grande': y})
    elif (views >= 1000):
        y = dict.get('medio')
        y+=1
        dict.update({'medio': y})
    else:
        y = dict.get('pequeño')
        y+=1
        dict.update({'pequeño': y})



print(dict)

{'pequeño': 1, 'medio': 2, 'grande': 3}


---
## Ejercicio 5 - Mapear IDs de juegos a nombres

La API de [Steam](https://store.steampowered.com/) devuelve datos con IDs numéricos. Tienes un diccionario de mapeo y una lista de horas jugadas por [**TheGrefg**](https://www.twitch.tv/thegrefg) (streamer y youtuber de gaming):

```python
id2game = {1172620: "Sea of Thieves", 1599340: "Lost Ark", 252490: "Rust", 578080: "PUBG"}
horas_jugadas = [(1172620, 320), (252490, 180), (578080, 95), (1172620, 150), (1599340, 200)]
```

Transforma la lista sustituyendo cada ID por el nombre del juego.

Resultado esperado:

```python
[("Sea of Thieves", 320), ("Rust", 180), ("PUBG", 95), ("Sea of Thieves", 150), ("Lost Ark", 200)]
```

In [10]:
id2game = {1172620: "Sea of Thieves", 1599340: "Lost Ark", 252490: "Rust", 578080: "PUBG"}
horas_jugadas = [(1172620, 320), (252490, 180), (578080, 95), (1172620, 150), (1599340, 200)]

### Solución

In [11]:
#Solución

tam = len(horas_jugadas)
lista =[]

for i in range(tam):
    x = horas_jugadas[i]
    if(id2game.get(x[0])):
        name = id2game.get(x[0])
        y = (name, x[1])
        lista.append(y)

print(lista)

[('Sea of Thieves', 320), ('Rust', 180), ('PUBG', 95), ('Sea of Thieves', 150), ('Lost Ark', 200)]


---
## Ejercicio 6 - Agrupar horas por juego

A partir de la lista transformada del ejercicio anterior:

```python
[("Sea of Thieves", 320), ("Rust", 180), ("PUBG", 95), ("Sea of Thieves", 150), ("Lost Ark", 200)]
```

Agrupa todas las horas por juego y construye un diccionario donde:

* La clave sea el nombre del juego.
* El valor sea la lista con todas las sesiones de horas registradas.

### Solución

In [12]:
#Solución
dict ={}
tam=len(lista)
for i in range(tam):
    x=lista[i]
    if(dict.get(x[0])):
        y = dict.get(x[0])
        y+=x[1]
        dict.update({x[0]:y})
    else:
        dict[x[0]]=x[1]

print(dict)


{'Sea of Thieves': 470, 'Rust': 180, 'PUBG': 95, 'Lost Ark': 200}


---

## Ejercicio 7 - Top-2 juegos más jugados

A partir del diccionario obtenido en el ejercicio anterior, calcula el **total de horas** de cada juego y genera una lista ordenada con los **dos juegos más jugados**, de mayor a menor.

El resultado debe ser una lista de pares `(juego, total_horas)`.

### Solución

In [13]:
#Solución
max1=0
max2=0
kmax=""
kmax2=""
tam=len(dict)
keys=dict.keys()
claves= list(keys)
for i in range(tam):
    x=dict.get(claves[i])
    if(max1<x):
        max2=max1
        kmax2=kmax
        max1=x
        kmax=claves[i]
    elif(max2<x):
        max2=x
        kmax2=claves[i]
        
lista=[{kmax,max1},{kmax2,max2}]
print(lista)


[{'Sea of Thieves', 470}, {200, 'Lost Ark'}]


---

## Ejercicio 8 - Normalizar ratings de canciones

Tienes ratings de canciones del álbum de [**Hijos de la Ruina**](https://es.wikipedia.org/wiki/Natos_y_Waor) formado por:
- [Natos y Waor](https://es.wikipedia.org/wiki/Natos_y_Waor) - dúo de rap español
- [Recycled J](https://es.wikipedia.org/wiki/Recycled_J) - rapero de Madrid

Los usuarios puntúan del 1 al 10:

```python
ratings = [7.8, 5.2, 9.5, 6.3]
```

Realiza las siguientes operaciones:

1. Redondea cada valor al número entero más cercano.
2. Normaliza los valores al rango **[0, 1]** usando min-max:

$$
x' = \frac{x - \min}{\max - \min}
$$

Devuelve dos listas: una con los valores redondeados y otra con los normalizados.

In [14]:
ratings = [7.8, 5.2, 9.5, 6.3]

### Solución

In [15]:
#Solución
redondeos=[]
norm=[]
maximo = max(ratings)
minimo = min(ratings)
for r in ratings:
    if(r%1>=0.5):
        redondeos.append((r//1)+1)
    else:
        redondeos.append(r//1)

    x=(r-minimo)/(maximo-minimo)
    norm.append(x)

print (redondeos)
print (norm)

[8.0, 5.0, 10.0, 6.0]
[0.6046511627906976, 0.0, 1.0, 0.25581395348837205]


---

## Ejercicio 9 - Rellenar datos faltantes de seguidores

Tienes un registro de seguidores diarios de influencers en Instagram, pero algunos días faltan datos (`None`):

- [AuronPlay](https://www.instagram.com/auronplay/) - streamer y youtuber
- [María Pombo](https://www.instagram.com/mariapombo/) - influencer

```python
seguidores = [("@auronplay", 2800000), ("@auronplay", None), ("@auronplay", 2820000), ("@mariapombo", None), ("@mariapombo", 3100000)]
```

Reemplaza cada `None` por el **último valor válido de ese mismo influencer** (forward fill).
Si no existe un valor previo válido, deja `None`.


In [16]:
seguidores = [("@auronplay", 2800000), ("@auronplay", None), ("@auronplay", 2820000), ("@mariapombo", None), ("@mariapombo", 3100000)]

### Solución

In [29]:
#Solución
dicSeg={}
i=0
for s in seguidores:
    if(dicSeg.get(s[0])==None):
        dicSeg.update({s[0]: s[1]})
    elif(s[1]==None and dicSeg[s[0]]!=None):
        seguidores[i]=(s[0],dicSeg[s[0]])
    i+=1

print (seguidores)



[('@auronplay', 2800000), ('@auronplay', 2800000), ('@auronplay', 2820000), ('@mariapombo', None), ('@mariapombo', 3100000)]


---

## Ejercicio 10 - Detectar picos de viralidad

Tienes las visualizaciones diarias de un vídeo de [**Diego Nister**](https://www.tiktok.com/@diegxnister) (creador de contenido español en TikTok):

```python
views = [45000, 52000, 48000, 850000, 1200000, 980000, 120000]
```

Detecta los índices donde el incremento respecto al día anterior supera las **500000 views**:

`views[i] - views[i-1] > 500000`

Estos picos indican que el vídeo se volvió **viral**. No se evalúa el primer elemento.


In [18]:
views = [45000, 52000, 48000, 850000, 1200000, 980000, 120000]
umbral = 500000

### Solución

In [33]:
#Solución
last=views[0]
for i in range(1,len(views)):
    if(views[i]-last>500000):
        print("Dia ",i,": se ha viralizado")
    last=views[i]

Dia  3 : se ha viralizado


---
## Ejercicio Extra — Análisis de hashtags en posts

Se pide analizar un archivo de texto con posts de redes sociales (estilo **Twitter/X**) para extraer la frecuencia de **hashtags**. Este tipo de análisis se usa para detectar tendencias como las que aparecen en los *trending topics*.

1. Lee el contenido completo del archivo.
2. Extrae todas las palabras que empiecen por `#`.
3. Normaliza a minúsculas y elimina signos de puntuación al final (como `.` o `,`).
4. Construye un diccionario con la frecuencia de cada hashtag.
5. Muestra el listado ordenado de mayor a menor frecuencia.


In [20]:
import string
from collections import Counter

def contar_hashtags(archivo):
    """
    Lee un archivo de texto y cuenta la aparición de cada hashtag.
    """
    try:
        with open(archivo, "r", encoding="utf-8") as f:
            texto = f.read().lower()

        #Continuar ...

    except FileNotFoundError:
        print("Error: El archivo no existe.")
        return {}
    except Exception as e:
        print(f"Ocurrió un error: {e}")
        return {}

def imprimirDiccionario(frecuencia_hashtags):
    #Completar ...
    pass

print("Inicio")
archivo = "texto_ibai.txt"
freq = contar_hashtags(archivo)
imprimirDiccionario(freq)


Inicio
Error: El archivo no existe.
